# Site variables
title: EmilieM
email: info@emiliem.be
baseurl: ""
url: https://dazzling-yalow-ba6079.netlify.com
twitter_username: jeromecoupe
github_username:  jeromecoupe
html_description: "Conseil en image - maquillage - massage"

# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

permalink: /blog/:title/

collections:
    - sections

# Defaults front matter variables for various types
# http://jekyllrb.com/docs/configuration/#front-matter-defaults
defaults:
-
  scope:
    path: ""
    type: "posts"
  values:
    layout: "blogpost"
    current_nav: "blog"
-
  scope:
    path: ""
    type: "projects"
  values:
    layout: "portfolio"
    current_nav: "work"

exclude:
  - node_modules
  - assets
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - package-lock.json
  - README.md
  - webpack.config.js

keep_files:
  - assets

plugins:
  - jekyll-menus